apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Chart.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    routes:
      - pattern: "/api/news"
        method:
          - "GET"
        backend_dns: "http://news-api-service.pro-homepage-back.svc.cluster.local:8080"