apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Chart.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    routes:
      - pattern: "/api/users"
        method:
          - "GET"
          - "POST"
        backend_dns: "http://localhost:8001"

      - pattern: "/api/posts"
        method:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
        backend_dns: "http://localhost:8002"

      - pattern: "/api/comments"
        method:
          - "GET"
          - "POST"
          - "PUT"
        backend_dns: "http://localhost:8003"

      - pattern: "/api/messages"
        method:
          - "GET"
          - "POST"
        backend_dns: "http://localhost:8004"
