apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    routes:
      - pattern: {{ .Values.config.routes.0.pattern | quote }}
        method: 
          {{- toYaml .Values.config.routes.0.method | nindent 10 }}
        backend_dns: {{ .Values.config.routes.0.backend_dns | quote }}
