apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Chart.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    routes:
      - pattern: "/api/posts"
        method:
          - "GET"
        backend_dns: "http://posts-service.pro-homepage-back.svc.cluster.local:80"