apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    routes:
      {{- range .Values.config.routes }}
      - pattern: {{ .pattern | quote }}
        method: 
          {{- toYaml .method | nindent 10 }}
        backend_dns: {{ .backend_dns | quote }}
      {{- end }}