apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 10003
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "app.fullname" . }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: '{{ include "app.fullname" . }}-container'
          image: harbor.server.local/danielbeltejar/common/apigw:latest 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 65532
            runAsGroup: 10002
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 1
            initialDelaySeconds: 3
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/config.yaml
              readOnly: true
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "app.fullname" . }}-config
