namespace: pro-homepage-back
replicaCount: 1
registry: harbor.server.local/danielbeltejar/homepage
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
extraEnv:
- name: "TZ"
  value: "UTC"
- name: "POSTS_DIR"
  value: "/app/posts"
extraEnvFrom: []
resources:
  requests:
    memory: "32Mi"
  limits:
    cpu: 500m
    memory: "128Mi"
volumeMounts:
- name: posts-data
  mountPath: /app/posts
  readOnly: true
volumes:
- name: posts-data
  persistentVolumeClaim:
    claimName: posts-data
