namespace: pre-homepage-back
replicaCount: 1
registry: harbor.server.local/danielbeltejar/homepage
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
extraEnv:
- name: "TZ"
  value: "UTC"
extraEnvFrom: []
resources:
  requests:
    memory: "32Mi"
  limits:
    memory: "128Mi"
