replicaCount: 1
namespace: pre-homepage-front
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
image:
  pullPolicy: Always
extraEnv:
- name: "TZ"
  value: "UTC"
extraEnvFrom: []
resources:
  requests:
    memory: "16Mi"
  limits:
    memory: "24Mi"
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-set-header: X-Real-IP $remote_addr
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  class: "nginx"
  host: "homepage.pre.server.local"
  tls: false
config:
  routes:
  - pattern: "/api/posts"
    method:
    - "GET"
    backend_dns: "http://posts-service.pre-homepage-back.svc.cluster.local:80"
