namespace: pre-homepage-front
replicaCount: 1
registry: harbor.server.local/danielbeltejar/homepage
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
extraEnv:
- name: "TZ"
  value: "UTC"
extraEnvFrom: []
resources:
  requests:
    memory: "32Mi"
  limits:
    memory: "128Mi"
volumes:
- name: tmpfs-var-lib-nginx-tmp
  emptyDir:
    medium: Memory
- name: tmpfs-run-nginx
  emptyDir:
    medium: Memory
volumeMounts:
- name: tmpfs-var-lib-nginx-tmp
  mountPath: /var/lib/nginx/tmp
- name: tmpfs-run-nginx
  mountPath: /run/nginx
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-set-header: X-Real-IP $remote_addr
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  class: "nginx-local"
  host: "homepage.pre.server.local"
  tls: true
