apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.backendFQDN }}
  ports:
    - port: {{ .Values.backendPort }}
      targetPort: {{ .Values.backendPort }}
      protocol: TCP
