{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "app.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}-backend
                port:
                  number: {{ .Values.backendPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
